---
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.13.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate_no_variables
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.6.2"
    hooks:
      - id: prettier
        args: ["--print-width=135"]
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.4
    hooks:
      - id: shellcheck
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: file-contents-sorter
        args: ["--ignore-case", "--unique"]
        files: "^.gitignore$"
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: trailing-whitespace

